'use client';

import { useEffect, useState } from 'react';
import { Topbar } from '@/components/layout/Topbar';
import { Card, CardHeader } from '@/components/ui/Card';
import { Badge, statusTone } from '@/components/ui/Badge';
import { LoadingPanel } from '@/components/ui/Skeleton';
import { Search, Sparkles } from 'lucide-react';
import { format } from 'date-fns';

interface Rfi {
  id: string;
  number: string;
  subject: string;
  question: string;
  discipline: string;
  status: string;
  submittedAt: string;
  answerText: string | null;
}
interface Match { rfiId: string; number: string; subject: string; similarity: number; status: string; hasAnswer: boolean }

export default function RfiKnowledgePage() {
  const [rfis, setRfis] = useState<Rfi[] | null>(null);
  const [query, setQuery] = useState('');
  const [matches, setMatches] = useState<Match[] | null>(null);
  const [answer, setAnswer] = useState<string | null>(null);
  const [model, setModel] = useState<string | null>(null);
  const [searching, setSearching] = useState(false);

  useEffect(() => {
    fetch('/api/agents/rfi')
      .then((r) => r.json())
      .then((d) => setRfis(d.rfis));
  }, []);

  const search = async () => {
    if (!query.trim()) return;
    setSearching(true);
    setMatches(null);
    setAnswer(null);
    const res = await fetch('/api/agents/rfi', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ question: query }),
    });
    const data = await res.json();
    setMatches(data.matches);
    setAnswer(data.suggestedAnswer);
    setModel(data.model);
    setSearching(false);
  };

  return (
    <>
      <Topbar title="Project Knowledge & RFI Intelligence Agent" subtitle="TF-IDF retrieval over the RFI corpus, synthesized answer suggestion" />
      <main className="flex-1 overflow-y-auto p-6">
        <Card className="mb-5">
          <CardHeader title="Ask a technical or contractual question" subtitle="Retrieval is deterministic (cosine similarity over prior RFIs); only the phrasing is generated by the LLM" />
          <div className="flex gap-2">
            <input
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && search()}
              placeholder="e.g. What is the required chilled water supply temperature tolerance?"
              className="flex-1 rounded border border-border bg-bg-primary px-3 py-2 text-sm text-text-primary placeholder:text-text-muted focus:border-accent focus:outline-none"
            />
            <button
              onClick={search}
              disabled={searching}
              className="flex items-center gap-1.5 rounded bg-accent px-4 py-2 text-sm font-medium text-white hover:bg-accent-hover disabled:opacity-50"
            >
              <Search size={14} />
              {searching ? 'Searching…' : 'Search'}
            </button>
          </div>

          {matches && (
            <div className="mt-4 space-y-3 border-t border-border pt-4">
              <div>
                <p className="mb-1.5 flex items-center gap-1.5 text-2xs font-semibold uppercase tracking-wide text-text-muted">
                  <Sparkles size={12} /> Suggested answer {model && <span className="normal-case text-text-muted">({model})</span>}
                </p>
                <p className="rounded border border-accent/30 bg-accent/5 p-3 text-sm text-text-secondary">{answer}</p>
              </div>
              <div>
                <p className="mb-1.5 text-2xs font-semibold uppercase tracking-wide text-text-muted">Retrieved similar RFIs</p>
                <div className="space-y-1.5">
                  {matches.map((m) => (
                    <div key={m.rfiId} className="flex items-center justify-between rounded border border-border px-3 py-1.5 text-2xs">
                      <span className="text-text-secondary"><span className="mono-tabular text-text-muted">{m.number}</span> · {m.subject}</span>
                      <div className="flex items-center gap-2">
                        <span className="mono-tabular text-text-muted">{(m.similarity * 100).toFixed(0)}% match</span>
                        <Badge tone={statusTone(m.status)}>{m.status}</Badge>
                      </div>
                    </div>
                  ))}
                  {matches.length === 0 && <p className="text-2xs text-text-muted">No sufficiently similar prior RFI found.</p>}
                </div>
              </div>
            </div>
          )}
        </Card>

        {!rfis && <LoadingPanel rows={5} />}
        {rfis && (
          <Card padded={false}>
            <div className="p-5 pb-0">
              <CardHeader title="RFI Log" subtitle={`${rfis.length} RFI(s) on record`} />
            </div>
            <div className="divide-y divide-border/60">
              {rfis.map((r) => (
                <div key={r.id} className="px-5 py-3">
                  <div className="mb-1 flex items-center justify-between">
                    <span className="text-sm text-text-primary"><span className="mono-tabular text-2xs text-text-muted">{r.number}</span> · {r.subject}</span>
                    <div className="flex items-center gap-2">
                      <span className="text-2xs text-text-muted">{format(new Date(r.submittedAt), 'dd MMM yyyy')}</span>
                      <Badge tone={statusTone(r.status)}>{r.status}</Badge>
                    </div>
                  </div>
                  <p className="text-2xs text-text-secondary">{r.question}</p>
                  {r.answerText && <p className="mt-1 border-l-2 border-accent/40 pl-2 text-2xs text-text-muted">{r.answerText}</p>}
                </div>
              ))}
            </div>
          </Card>
        )}
      </main>
    </>
  );
}
